export const siteConfig = {
  name: "Alexis Olivero",
  title: "Frontend Developer & Web Specialist",
  description:
    "Frontend Developer with over 6 years of experience delivering high-impact web solutions. Specialized in WordPress, Webflow, and React, with a strong focus on building scalable, maintainable architectures.",
  url: "https://oliverodev.com",
  ogImage: "https://oliverodev.com/opengraph-image",
  links: {
    instagram: "https://www.instagram.com/alexisfit97/",
    github: "https://github.com/wolfslender",
    linkedin: "https://linkedin.com/in/alexis-olivero",
    email: "contact@oliverodev.com",
  },
  author: "Alexis Olivero",
  keywords: [
    "frontend developer",
    "desarrollador frontend",
    "web developer",
    "desarrollador web",
    "react developer",
    "programador react",
    "next.js expert",
    "typescript",
    "javascript",
    "tailwind css",
    "wordpress specialist",
    "experto wordpress",
    "webflow developer",
    "desarrollador webflow",
    "seo optimization",
    "posicionamiento seo",
    "web performance",
    "optimización web",
    "ui/ux design",
    "diseño web",
    "freelance developer",
    "programador freelance",
    "hire web developer",
    "hire frontend developer",
    "contratar desarrollador web",
    "contratar desarrollador frontend",
    "web developer for hire",
    "frontend freelancer",
    "alexis olivero",
    "portfolio",
  ],
  navItems: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Work", href: "/work" },
    { label: "Blog", href: "/blog" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
}

export type SiteConfig = typeof siteConfig
