import { Code, Users, Award, Coffee, Code2, Server, Database, GitBranch, Palette, Smartphone, Zap, Rocket, Search, Globe, Layout, Shield, Brain, MessageSquare, Clock, Users2, Cloud, FileCode } from "lucide-react"

export const services = [
  {
    title: "Web Development",
    description: "Custom websites built with React, Next.js, or WordPress. Fast, secure, and SEO-optimized.",
    icon: Code2,
    features: ["Custom Development", "CMS Integration", "Performance Optimization", "SEO Best Practices"],
    technologies: ["React", "Next.js", "TypeScript", "Tailwind"],
    price: "Custom",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  {
    title: "Webflow Development",
    description: "High-end Webflow sites with advanced animations and interactions. Perfect for marketing sites.",
    icon: Layout,
    features: ["Visual Development", "Complex Animations", "CMS Setup", "Pixel-Perfect Design"],
    technologies: ["Webflow", "GSAP", "JavaScript", "Figma"],
    price: "Custom",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
  },
  {
    title: "Performance Optimization",
    description: "Speed up your existing website. Improve Core Web Vitals, user retention, and Google rankings.",
    icon: Zap,
    features: ["Load Time Reduction", "Image Optimization", "Code Minification", "Caching Strategies"],
    technologies: ["Lighthouse", "Vercel Analytics", "Web Vitals", "CDN"],
    price: "Starting at $250",
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
  },
  {
    title: "Cloud & Web Security",
    description: "Secure server management (Azure/AWS), deployment strategies, and implementation of strict security protocols for digital assets.",
    icon: Shield,
    features: ["Azure/AWS Management", "Security Audits", "Server Hardening", "Deployment Pipelines"],
    technologies: ["Azure", "AWS", "Docker", "Linux"],
    price: "Custom",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
]

export const hero = {
  title: {
    prefix: "Building digital",
    highlight: "products, brands, and experiences",
  },
  roles: ["Tech Lead", "Frontend Developer", "Web Security Enthusiast", "Cloud Architect"],
  description: "Frontend Developer with over 8 years of experience delivering high-impact web solutions. Specialized in WordPress, Webflow, and React, with a strong focus on building scalable, maintainable architectures and crafting exceptional user experiences.",
  buttons: {
    primary: "View Work",
    secondary: "Contact Me",
    downloadCv: "Download CV",
  },
}

export const stats = [
  { icon: Code, value: 8, label: "Years Experience", suffix: "+", prefix: "" },
  { icon: Users, value: 50, label: "Projects Delivered", suffix: "+", prefix: "" },
  { icon: Award, value: 100, label: "Client Satisfaction", suffix: "%", prefix: "" },
  { icon: Zap, value: 30, label: "Faster Load Times", suffix: "%", prefix: "" },
]

export const skills = [
  {
    icon: Code2,
    title: "Frontend",
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    skills: ["HTML5", "CSS3", "JavaScript (ES6+)", "React.js", "Next.js", "Tailwind CSS", "Sass/LESS"],
  },
  {
    icon: Globe,
    title: "CMS & Platforms",
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
    skills: ["WordPress", "Webflow", "WooCommerce", "Shopify", "CPanel"],
  },
  {
    icon: Zap,
    title: "Performance",
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
    skills: ["SEO", "Core Web Vitals", "Accessibility (WCAG)", "Responsive Design", "Optimization"],
  },
  {
    icon: GitBranch,
    title: "Tools & DevOps",
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    skills: ["Git", "GitHub", "Azure", "Docker", "VS Code", "Chrome DevTools"],
  },
  {
    icon: Palette,
    title: "Design",
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
    skills: ["UI/UX Principles", "Figma", "Wireframing", "Prototyping", "User-Centered Design"],
  },
  {
    icon: Shield,
    title: "Security",
    color: "text-green-500",
    bgColor: "bg-green-500/10",
    skills: ["Web Security", "Data Protection", "Secure Coding", "Server Hardening", "OWASP Top 10"],
  },
]

export const softSkills = [
  { icon: MessageSquare, label: "Communication" },
  { icon: Brain, label: "Problem Solving" },
  { icon: Users2, label: "Teamwork" },
  { icon: Clock, label: "Time Management" },
  { icon: Rocket, label: "Adaptability" },
  { icon: Palette, label: "Creativity" },
]

export const certifications = [
  {
    title: "Scrum Fundamentals Certified (SFC)",
    issuer: "VMEdu Inc.",
    date: "Feb 2025",
    credentialId: "1066047",
    credentialUrl: "#",
    icon: Users2,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
  },
  {
    title: "Webflow 101 Certification",
    issuer: "Webflow",
    date: "Nov 2023",
    credentialId: "Alexis Olivero Canario",
    credentialUrl: "#",
    icon: Layout,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },

  {
    title: "Information Technology Fundamentals",
    issuer: "IBM",
    date: "May 2025",
    credentialId: "IBM-2025",
    credentialUrl: "#",
    icon: Server,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
  },
  {
    title: "Hacking Ético en Acción",
    issuer: "Desafío Latam",
    date: "Mar 2025",
    credentialId: "5m77bnugwj",
    credentialUrl: "#",
    icon: Shield,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
  },
  {
    title: "Fundamentos de AWS Cloud Services",
    issuer: "LinkedIn",
    date: "Sep 2022",
    credentialId: "AWS-LI",
    credentialUrl: "#",
    icon: Cloud,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10",
  },
  {
    title: "Azure: Bases de datos SQL",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "AZURE-SQL",
    credentialUrl: "#",
    icon: Database,
    color: "text-cyan-500",
    bgColor: "bg-cyan-500/10",
  },
  {
    title: "React Esencial",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "REACT-LI",
    credentialUrl: "#",
    icon: Code2,
    color: "text-sky-500",
    bgColor: "bg-sky-500/10",
  },
  {
    title: "Domina JavaScript",
    issuer: "LinkedIn",
    date: "Sep 2023",
    credentialId: "JS-LI",
    credentialUrl: "#",
    icon: FileCode,
    color: "text-yellow-400",
    bgColor: "bg-yellow-400/10",
  },
  {
    title: "GitHub para Programadores",
    issuer: "LinkedIn",
    date: "Jun 2023",
    credentialId: "GH-LI",
    credentialUrl: "#",
    icon: GitBranch,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  },
]

export const projects = [
  {
    title: "Co-Active Training Institute",
    description: "Ongoing fullstack development and maintenance for a global leadership training platform. Responsible for SEO strategies, performance optimization, and implementing new features for a site serving over 150k professionals worldwide.",
    image: "/projects/coactive.jpg",
    tags: ["Fullstack", "SEO", "Performance", "Maintenance"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://coactive.com/",
    featured: true,
    size: "large",
  },
  {
    title: "Departamento de Educación PR",
    description:
      "Led end-to-end development of a government website for Puerto Rico. Delivered a responsive, accessible, and CMS-integrated solution aligned with public sector standards.",
    image: "/projects/departamento-educacion.jpg",
    tags: ["WordPress", "PHP", "Tailwind CSS", "MySQL"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://de.pr.gov/",
    featured: true,
    size: "large",
  },
  {
    title: "CST Puerto Rico Website",
    description: "Government project focused on traffic safety. Includes CMS, incident reports, interactive maps, and community feedback tools.",
    image: "/projects/cst-puerto-rico.jpg",
    tags: ["Next.js", "Sanity CMS", "Tailwind CSS"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://www.cst.pr.gov/",
    featured: true,
    size: "large",
  },
  {
    title: "Truenorth Corporation",
    description: "Migrated corporate website from WordPress to Webflow, rebuilding the frontend and integrating custom API functionalities for better performance.",
    image: "/projects/truenorth.jpg",
    tags: ["Webflow", "React", "Node.js"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://www.truenorth.pr/",
    featured: true,
    size: "medium",
  },
  {
    title: "D.Med Healthcare Group",
    description: "Developed a drag-and-drop task management app with real-time updates, team collaboration, and authentication features.",
    image: "/projects/dmed.jpg",
    tags: ["PHP", "Docker", "JavaScript", "MySQL"],
    category: "fullstack",
    github: "https://github.com/wolfslender",
    demo: "https://dmed-healthcare.com/",
    featured: false,
    size: "medium",
  },
  {
    title: "GovValue",
    description: "Dynamic blog system with SEO optimization, author management, and custom call-to-action banners to attract new users.",
    image: "/projects/govvalue.jpg",
    tags: ["React", "JavaScript", "CSS Grid", "SEO"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://govvalue.com/",
    featured: false,
    size: "medium",
  },
  {
    title: "AESAN Website",
    description: "Official website for the Government of Puerto Rico. Responsive, accessible platform aligned with public health communication standards.",
    image: "/projects/aesan.jpg",
    tags: ["JavaScript", "DataTables", "API Integration"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://aesan.dde.pr/",
    featured: false,
    size: "medium",
  },
  {
    title: "Centro de Sonografía PRE-VUE",
    description: "Official website for PRE-VUE Sonography Center in Puerto Rico. Features AI-powered 4D/HD Live imaging services, appointment scheduling, and a holistic wellness center integration.",
    image: "/projects/pre-vue.webp",
    tags: ["Next.js", "React", "Tailwind CSS", "Framer Motion"],
    category: "frontend",
    github: "https://github.com/wolfslender",
    demo: "https://pre-vue.com/",
    featured: true,
    size: "medium",
  },
]

export const experience = [
  {
    company: "Co-Active Training Institute",
    position: "Frontend Web Developer (Part-time)",
    period: "2025 - Present",
    location: "Remote",
    description: "Collaborating on the maintenance and evolution of the main digital platform.",
    technologies: ["React", "JavaScript", "UI/UX", "Agile"],
    achievements: [
      "Contributing to the improvement of the user interface",
      "Participating in agile development cycles",
    ],
  },
  {
    company: "Dmed health care",
    position: "WordPress Specialist & Web Developer",
    period: "2018 - 2022",
    location: "Remote",
    description: "Led the development and maintenance of corporate websites using WordPress, focusing on custom themes and performance.",
    technologies: ["WordPress", "PHP", "MySQL", "JavaScript", "Custom Themes"],
    achievements: [
      "Developed and maintained custom WordPress themes and plugins",
      "Optimized site performance and security protocols",
      "Managed content updates and technical troubleshooting",
    ],
  },
  {
    company: "TRUENORTH Corp.",
    position: "Frontend Web Developer",
    period: "2022 - 2025",
    location: "Santo Domingo",
    description: "Specializing in web security, maintenance, SEO, and site management on Azure servers. Focused on performance optimization and usability.",
    technologies: ["WordPress", "WebFlow", "SEO", "Azure", "JavaScript", "CSS3"],
    achievements: [
      "Achieved a 25% increase in user retention",
      "Reduced loading times by 30% through optimization",
      "Implemented custom CMS solutions boosting efficiency by 40%",
      "Developed 15+ web projects with WebFlow",
    ],
  },
  {
    company: "CYBERNETIPS",
    position: "Fullstack Web Developer",
    period: "2017 - 2018",
    location: "Miami, FL (Remote)",
    description: "Specializing in backend development from scratch for high-traffic, large-scale projects and server administration.",
    technologies: ["HTML", "CSS", "JavaScript", "CPanel", "Cloud Architecture"],
    achievements: [
      "Managed and optimized servers in CPanel and Cloud environments",
      "Led optimization and maintenance of Cloud-based systems",
      "Ensured high availability and security of digital assets",
    ],
  },
]

export const education = [
  {
    school: "Liceo Minerva Mirabal",
    degree: "Computer Science, Bachelor's Degree",
    period: "Jun 2012 - Sep 2015",
    location: "Santo Domingo",
    description: "Graduated with a strong foundation in programming, algorithms, and information systems.",
  },
]

export const contact = {
  email: "contact@oliverodev.com",
  phone: "(829) 983-2502",
  location: "Santo Domingo, Dominican Republic",
  social: {
    github: "https://github.com/wolfslender",
    linkedin: "https://linkedin.com/in/alexis-olivero",
    instagram: "https://www.instagram.com/alexisfit97/",
  },
}
